import * as XLSX from 'xlsx';

// PDF Export using html2pdf
export const exportToPDF = async (data, filename = 'rewixx-report.pdf') => {
  return new Promise((resolve, reject) => {
    // Load html2pdf if not already loaded
    if (!window.html2pdf) {
      const script = document.createElement('script');
      script.src = 'https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js';
      script.onload = () => generatePDF(data, filename, resolve, reject);
      script.onerror = () => reject(new Error('Failed to load html2pdf library'));
      document.head.appendChild(script);
    } else {
      generatePDF(data, filename, resolve, reject);
    }
  });
};

const generatePDF = (data, filename, resolve, reject) => {
  try {
    const element = document.createElement('div');
    element.innerHTML = generatePDFContent(data);
    element.style.position = 'absolute';
    element.style.left = '-9999px';
    element.style.top = '0';
    document.body.appendChild(element);

    const opt = {
      margin: 10,
      filename: filename,
      image: { type: 'jpeg', quality: 0.95 },
      html2canvas: { scale: 2, useCORS: true },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
      pagebreak: { mode: ['css', 'legacy'] }
    };

    window.html2pdf().set(opt).from(element).save().then(() => {
      document.body.removeChild(element);
      resolve();
    }).catch(reject);
  } catch (error) {
    reject(error);
  }
};

const generatePDFContent = (data) => {
  const currentDate = new Date().toLocaleDateString();
  return `
    <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
      <div style="text-align: center; margin-bottom: 30px; border-bottom: 2px solid #3b82f6; padding-bottom: 20px;">
        <img src="/logo.png" alt="Rewixx Logo" style="height: 60px; margin-bottom: 10px;">
        <h1 style="color: #3b82f6; margin: 0; font-size: 28px;">Rewixx Business Report</h1>
        <p style="color: #666; margin: 5px 0;">Generated on ${currentDate}</p>
      </div>

      ${data.revenue ? generateRevenueSection(data.revenue) : ''}
      ${data.labor ? generateLaborSection(data.labor) : ''}
      ${data.expenses ? generateExpensesSection(data.expenses) : ''}
      ${data.insights ? generateInsightsSection(data.insights) : ''}

      <div style="margin-top: 40px; text-align: center; color: #666; font-size: 12px;">
        <p>This report was generated by Rewixx Cloud App - Your trusted business management solution</p>
      </div>
    </div>
  `;
};

const generateRevenueSection = (revenue) => `
  <div style="margin-bottom: 30px;">
    <h2 style="color: #22c55e; border-bottom: 1px solid #22c55e; padding-bottom: 5px;">💰 Revenue Analysis</h2>
    <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin: 20px 0;">
      <div style="background: #f0fdf4; padding: 15px; border-radius: 8px; border-left: 4px solid #22c55e;">
        <h3 style="margin: 0 0 5px 0; color: #166534;">Total Revenue</h3>
        <p style="margin: 0; font-size: 24px; font-weight: bold; color: #22c55e;">$${revenue.summary?.totalRevenue?.toFixed(2) || '0.00'}</p>
      </div>
      <div style="background: #f0f9ff; padding: 15px; border-radius: 8px; border-left: 4px solid #3b82f6;">
        <h3 style="margin: 0 0 5px 0; color: #1e40af;">Materials Cost</h3>
        <p style="margin: 0; font-size: 24px; font-weight: bold; color: #3b82f6;">$${revenue.summary?.totalMaterials?.toFixed(2) || '0.00'}</p>
      </div>
      <div style="background: #fef3c7; padding: 15px; border-radius: 8px; border-left: 4px solid #f59e0b;">
        <h3 style="margin: 0 0 5px 0; color: #92400e;">Labor Cost</h3>
        <p style="margin: 0; font-size: 24px; font-weight: bold; color: #f59e0b;">$${revenue.summary?.totalLabor?.toFixed(2) || '0.00'}</p>
      </div>
      <div style="background: #faf5ff; padding: 15px; border-radius: 8px; border-left: 4px solid #8b5cf6;">
        <h3 style="margin: 0 0 5px 0; color: #6b21a8;">Net Profit</h3>
        <p style="margin: 0; font-size: 24px; font-weight: bold; color: #8b5cf6;">$${((revenue.summary?.totalRevenue || 0) - (revenue.summary?.totalMaterials || 0) - (revenue.summary?.totalLabor || 0)).toFixed(2)}</p>
      </div>
    </div>
  </div>
`;

const generateLaborSection = (labor) => `
  <div style="margin-bottom: 30px;">
    <h2 style="color: #3b82f6; border-bottom: 1px solid #3b82f6; padding-bottom: 5px;">⏰ Labor Analysis</h2>
    <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin: 20px 0;">
      <div style="background: #f0f9ff; padding: 15px; border-radius: 8px; border-left: 4px solid #3b82f6;">
        <h3 style="margin: 0 0 5px 0; color: #1e40af;">Estimated Hours</h3>
        <p style="margin: 0; font-size: 24px; font-weight: bold; color: #3b82f6;">${labor.summary?.totalEstimatedHours || 0} hrs</p>
      </div>
      <div style="background: #f0fdf4; padding: 15px; border-radius: 8px; border-left: 4px solid #22c55e;">
        <h3 style="margin: 0 0 5px 0; color: #166534;">Actual Hours</h3>
        <p style="margin: 0; font-size: 24px; font-weight: bold; color: #22c55e;">${labor.summary?.totalActualHours || 0} hrs</p>
      </div>
      <div style="background: #fef3c7; padding: 15px; border-radius: 8px; border-left: 4px solid #f59e0b;">
        <h3 style="margin: 0 0 5px 0; color: #92400e;">Efficiency</h3>
        <p style="margin: 0; font-size: 24px; font-weight: bold; color: #f59e0b;">${labor.summary?.efficiency?.toFixed(1) || 0}%</p>
      </div>
      <div style="background: #faf5ff; padding: 15px; border-radius: 8px; border-left: 4px solid #8b5cf6;">
        <h3 style="margin: 0 0 5px 0; color: #6b21a8;">Labor Cost</h3>
        <p style="margin: 0; font-size: 24px; font-weight: bold; color: #8b5cf6;">$${labor.summary?.totalLaborCost?.toFixed(2) || '0.00'}</p>
      </div>
    </div>
  </div>
`;

const generateExpensesSection = (expenses) => `
  <div style="margin-bottom: 30px;">
    <h2 style="color: #f59e0b; border-bottom: 1px solid #f59e0b; padding-bottom: 5px;">💳 Expenses Analysis</h2>
    <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin: 20px 0;">
      <div style="background: #f0fdf4; padding: 15px; border-radius: 8px; border-left: 4px solid #22c55e;">
        <h3 style="margin: 0 0 5px 0; color: #166534;">Billable Expenses</h3>
        <p style="margin: 0; font-size: 24px; font-weight: bold; color: #22c55e;">$${expenses.summary?.totalBillableExpenses?.toFixed(2) || '0.00'}</p>
      </div>
      <div style="background: #fef3c7; padding: 15px; border-radius: 8px; border-left: 4px solid #f59e0b;">
        <h3 style="margin: 0 0 5px 0; color: #92400e;">Non-Billable</h3>
        <p style="margin: 0; font-size: 24px; font-weight: bold; color: #f59e0b;">$${expenses.summary?.totalNonBillableExpenses?.toFixed(2) || '0.00'}</p>
      </div>
      <div style="background: #f0f9ff; padding: 15px; border-radius: 8px; border-left: 4px solid #3b82f6;">
        <h3 style="margin: 0 0 5px 0; color: #1e40af;">Total Expenses</h3>
        <p style="margin: 0; font-size: 24px; font-weight: bold; color: #3b82f6;">$${expenses.summary?.totalExpenses?.toFixed(2) || '0.00'}</p>
      </div>
      <div style="background: #faf5ff; padding: 15px; border-radius: 8px; border-left: 4px solid #8b5cf6;">
        <h3 style="margin: 0 0 5px 0; color: #6b21a8;">Billable Ratio</h3>
        <p style="margin: 0; font-size: 24px; font-weight: bold; color: #8b5cf6;">${expenses.summary?.billableRatio?.toFixed(1) || 0}%</p>
      </div>
    </div>
  </div>
`;

const generateInsightsSection = (insights) => `
  <div style="margin-bottom: 30px;">
    <h2 style="color: #8b5cf6; border-bottom: 1px solid #8b5cf6; padding-bottom: 5px;">🎯 Business Insights</h2>
    <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin: 20px 0;">
      <div style="background: #f0f9ff; padding: 15px; border-radius: 8px; border-left: 4px solid #3b82f6;">
        <h3 style="margin: 0 0 5px 0; color: #1e40af;">Active Customers</h3>
        <p style="margin: 0; font-size: 24px; font-weight: bold; color: #3b82f6;">${insights.overview?.activeCustomers || 0}</p>
      </div>
      <div style="background: #f0fdf4; padding: 15px; border-radius: 8px; border-left: 4px solid #22c55e;">
        <h3 style="margin: 0 0 5px 0; color: #166534;">Total Revenue</h3>
        <p style="margin: 0; font-size: 24px; font-weight: bold; color: #22c55e;">$${insights.overview?.totalRevenue?.toFixed(2) || '0.00'}</p>
      </div>
      <div style="background: #fef3c7; padding: 15px; border-radius: 8px; border-left: 4px solid #f59e0b;">
        <h3 style="margin: 0 0 5px 0; color: #92400e;">Efficiency</h3>
        <p style="margin: 0; font-size: 24px; font-weight: bold; color: #f59e0b;">${insights.efficiency?.efficiency?.toFixed(1) || 0}%</p>
      </div>
      <div style="background: #faf5ff; padding: 15px; border-radius: 8px; border-left: 4px solid #8b5cf6;">
        <h3 style="margin: 0 0 5px 0; color: #6b21a8;">Completion Rate</h3>
        <p style="margin: 0; font-size: 24px; font-weight: bold; color: #8b5cf6;">${insights.overview?.totalJobs > 0 ? Math.round((insights.overview.completedJobs / insights.overview.totalJobs) * 100) : 0}%</p>
      </div>
    </div>
  </div>
`;

// Excel Export
export const exportToExcel = async (data, filename = 'rewixx-report.xlsx') => {
  try {
    const workbook = XLSX.utils.book_new();
    
    // Revenue sheet
    if (data.revenue) {
      const revenueData = [
        ['Revenue Analysis'],
        ['Metric', 'Value'],
        ['Total Revenue', data.revenue.summary?.totalRevenue || 0],
        ['Materials Cost', data.revenue.summary?.totalMaterials || 0],
        ['Labor Cost', data.revenue.summary?.totalLabor || 0],
        ['Net Profit', (data.revenue.summary?.totalRevenue || 0) - (data.revenue.summary?.totalMaterials || 0) - (data.revenue.summary?.totalLabor || 0)],
        [''],
        ['Revenue by Customer'],
        ['Customer', 'Revenue']
      ];
      
      if (data.revenue.revenueByCustomer) {
        Object.entries(data.revenue.revenueByCustomer).forEach(([customer, revenue]) => {
          revenueData.push([customer, revenue]);
        });
      }
      
      const revenueSheet = XLSX.utils.aoa_to_sheet(revenueData);
      XLSX.utils.book_append_sheet(workbook, revenueSheet, 'Revenue');
    }
    
    // Labor sheet
    if (data.labor) {
      const laborData = [
        ['Labor Analysis'],
        ['Metric', 'Value'],
        ['Estimated Hours', data.labor.summary?.totalEstimatedHours || 0],
        ['Actual Hours', data.labor.summary?.totalActualHours || 0],
        ['Efficiency (%)', data.labor.summary?.efficiency || 0],
        ['Labor Cost', data.labor.summary?.totalLaborCost || 0]
      ];
      
      const laborSheet = XLSX.utils.aoa_to_sheet(laborData);
      XLSX.utils.book_append_sheet(workbook, laborSheet, 'Labor');
    }
    
    // Expenses sheet
    if (data.expenses) {
      const expensesData = [
        ['Expenses Analysis'],
        ['Metric', 'Value'],
        ['Billable Expenses', data.expenses.summary?.totalBillableExpenses || 0],
        ['Non-Billable Expenses', data.expenses.summary?.totalNonBillableExpenses || 0],
        ['Total Expenses', data.expenses.summary?.totalExpenses || 0],
        ['Billable Ratio (%)', data.expenses.summary?.billableRatio || 0]
      ];
      
      const expensesSheet = XLSX.utils.aoa_to_sheet(expensesData);
      XLSX.utils.book_append_sheet(workbook, expensesSheet, 'Expenses');
    }
    
    // Insights sheet
    if (data.insights) {
      const insightsData = [
        ['Business Insights'],
        ['Metric', 'Value'],
        ['Total Jobs', data.insights.overview?.totalJobs || 0],
        ['Completed Jobs', data.insights.overview?.completedJobs || 0],
        ['Active Customers', data.insights.overview?.activeCustomers || 0],
        ['Total Revenue', data.insights.overview?.totalRevenue || 0],
        ['Efficiency (%)', data.insights.efficiency?.efficiency || 0]
      ];
      
      const insightsSheet = XLSX.utils.aoa_to_sheet(insightsData);
      XLSX.utils.book_append_sheet(workbook, insightsSheet, 'Insights');
    }
    
    XLSX.writeFile(workbook, filename);
  } catch (error) {
    throw new Error(`Failed to export Excel file: ${error.message}`);
  }
};

// CSV Export
export const exportToCSV = async (data, filename = 'rewixx-report.csv') => {
  try {
    let csvContent = 'Rewixx Business Report\n';
    csvContent += `Generated on: ${new Date().toLocaleDateString()}\n\n`;
    
    if (data.revenue) {
      csvContent += 'REVENUE ANALYSIS\n';
      csvContent += 'Metric,Value\n';
      csvContent += `Total Revenue,${data.revenue.summary?.totalRevenue || 0}\n`;
      csvContent += `Materials Cost,${data.revenue.summary?.totalMaterials || 0}\n`;
      csvContent += `Labor Cost,${data.revenue.summary?.totalLabor || 0}\n`;
      csvContent += `Net Profit,${(data.revenue.summary?.totalRevenue || 0) - (data.revenue.summary?.totalMaterials || 0) - (data.revenue.summary?.totalLabor || 0)}\n\n`;
    }
    
    if (data.labor) {
      csvContent += 'LABOR ANALYSIS\n';
      csvContent += 'Metric,Value\n';
      csvContent += `Estimated Hours,${data.labor.summary?.totalEstimatedHours || 0}\n`;
      csvContent += `Actual Hours,${data.labor.summary?.totalActualHours || 0}\n`;
      csvContent += `Efficiency (%),${data.labor.summary?.efficiency || 0}\n`;
      csvContent += `Labor Cost,${data.labor.summary?.totalLaborCost || 0}\n\n`;
    }
    
    if (data.expenses) {
      csvContent += 'EXPENSES ANALYSIS\n';
      csvContent += 'Metric,Value\n';
      csvContent += `Billable Expenses,${data.expenses.summary?.totalBillableExpenses || 0}\n`;
      csvContent += `Non-Billable Expenses,${data.expenses.summary?.totalNonBillableExpenses || 0}\n`;
      csvContent += `Total Expenses,${data.expenses.summary?.totalExpenses || 0}\n`;
      csvContent += `Billable Ratio (%),${data.expenses.summary?.billableRatio || 0}\n\n`;
    }
    
    if (data.insights) {
      csvContent += 'BUSINESS INSIGHTS\n';
      csvContent += 'Metric,Value\n';
      csvContent += `Total Jobs,${data.insights.overview?.totalJobs || 0}\n`;
      csvContent += `Completed Jobs,${data.insights.overview?.completedJobs || 0}\n`;
      csvContent += `Active Customers,${data.insights.overview?.activeCustomers || 0}\n`;
      csvContent += `Total Revenue,${data.insights.overview?.totalRevenue || 0}\n`;
      csvContent += `Efficiency (%),${data.insights.efficiency?.efficiency || 0}\n`;
    }
    
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', filename);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  } catch (error) {
    throw new Error(`Failed to export CSV file: ${error.message}`);
  }
};
